---
- name: php7 - install xdebug
  apt: pkg=php-xdebug state=latest update_cache=yes

- name: Copy xdebug INI into mods-available folder.
  template: >
    src=xdebug.ini.j2
    dest={{ item }}
    owner=root group=root mode=644
  with_items: "{{'/etc/php/*/mods-available/xdebug.ini' | fileglob}}"
